apiVersion: v1
kind: Namespace
metadata:
  name: libsql
---
apiVersion: v1
kind: Namespace
metadata:
  name: immich
---
apiVersion: v1
kind: Namespace
metadata:
  name: backup
---
apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: v1
kind: Namespace
metadata:
  name: tuwunel
---
apiVersion: v1
kind: Namespace
metadata:
  name: zeroclaw
