tunnel: REPLACE_WITH_TUNNEL_UUID
credentials-file: /var/lib/secrets/cloudflared/REPLACE_WITH_TUNNEL_UUID.json

ingress:
  - hostname: db.aza.network
    service: http://127.0.0.1:80

  - hostname: photos.aza.network
    service: http://127.0.0.1:80
    originRequest:
      access:
        required: true
        teamName: REPLACE_WITH_CF_TEAM_NAME
        audTag:
          - REPLACE_WITH_PHOTOS_AUD_TAG

  - hostname: kopia.aza.network
    service: http://127.0.0.1:80
    originRequest:
      access:
        required: true
        teamName: REPLACE_WITH_CF_TEAM_NAME
        audTag:
          - REPLACE_WITH_KOPIA_AUD_TAG

  - hostname: vault.aza.network
    service: http://127.0.0.1:80

  - service: http_status:404
