apiVersion: ENC[AES256_GCM,data:r7U=,iv:hyfNiK13Mbg048ED8gSTFJT2vaVTo+DpfV6RzVI6WMc=,tag:ZAknQaXnUGiRvaGI6RBmJA==,type:str]
kind: ENC[AES256_GCM,data:Wwp6/TAl,iv:y7EBKXMPS4zHZmqWupFBEInhqZBMDXBvUyS9lafQhOU=,tag:gkA38eH05EQQjLGg0eRepA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nSYQHS2L1V+EElQ=,iv:vHp23UeAwwIMLm/WuCbSz46TrbwCSy5uR3BqIqY31zE=,tag:aMKqZlaq2cFO5J4y3Wt5Gw==,type:str]
    namespace: ENC[AES256_GCM,data:P/de9Nio,iv:tNV2gBbR945ioKZOimWf/TtwHLnUWMjGZpnJwBk22K4=,tag:CW0vVJrRlPsqZ7j5EtqG5g==,type:str]
type: ENC[AES256_GCM,data:718USiRH,iv:BAgEzaEdwu1Xbpin9u2wNyOnb78kEweDaRrR+IOweL0=,tag:CQ7BMUHSeWXMZNl4JNzKiQ==,type:str]
stringData:
    SQLD_AUTH_JWT_KEY: ENC[AES256_GCM,data:5aiywKbMyD6AQSTK8NnVxCzkyTsnZj05oasghcp3JC3+x5aRTqntgeoeVw==,iv:SnkCpR67kSN3pF5JjkMFpurchHXQypgWUjOL8fkoDyY=,tag:M2Kpji7piZW4rvWaCdnJZw==,type:str]
    SQLD_AUTH_JWT_PRIVATE_KEY_PEM: ENC[AES256_GCM,data:LzhYJ+n/5mVaJ/yylyMln435f/LE5i8R4FrSrX5rTgjDO2v2RQNiowlnVq4C73usPbDKAXWRRUIR79I77GgqkxHccHNUQkcXd+PmttIVEyKVaK2QL9kUGfNy9GwqkPwHFTXGKCa5NFi7RrpJ/m0e6dWF3pjz1g==,iv:2oHwnuu3bzhQQ1qQbxuRrC/oYBu35Zxv6V/5KBKmjNM=,tag:U1TcxcMTHXEjja4/4cFUWA==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTi9iQ21POGFQTTZ5Z3R1
            UUdOTERuRThKWGZNSi9RNFROdTB4ZzhkekVjCnFSRCtBVEo2eHlxbXZuSllUeng1
            Mk82ZmRJOFUrcm5IS1hnb2MvVDV1SGMKLS0tIFFsRjlWRllWSGRQN3J0aW53VENP
            bTdMZ1RPWW5mYmg2KzB2SVhiclhGQzAK75ny0Egqsd/9yHl60J3nAEuKZGvynUKS
            YGnT5Yjx/yID2/Rh8k3Fhm89DiwLBZsmVetMlb9uKoyIrXoTkETr8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T09:28:36Z"
    mac: ENC[AES256_GCM,data:By2jvTAgeEjNWm1yqk/bDma+cZ+XzIkgRcwVTO/uSzFeU1UyKRO9W0f6BwOCUr3614rKdbo9lmMSL3RCydzQZleHKHwzl1Ozgl14sBQ1SEV8C8otfawMGAeHc0ca58P70aZscZ4HR+Oyy2N+uYWWr8MfBCkMDMnX4d2gmgBLDpM=,iv:2vUpl+8W7T+ZfFvx9OZ/ftHD2fZviM1mgGaldZrv4GA=,tag:ZNe/WwFMTB4jyh9fnTKNXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:0Ko=,iv:jlUPdTcr8cE8sO8wNPboKY0giA/5ygOVPfZbc1evWQI=,tag:b7z8UTVotGUdf9Az1feJCw==,type:str]
kind: ENC[AES256_GCM,data:5oNq4+uI,iv:TT17/t3cOxx1gtxKx2tgldzJl4fZ4Fe9hZri6Re7LIc=,tag:UiLkbsOXSduBEIQ3xpH7zA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6AdCxaPmPTj5Ug==,iv:7q3qpsaYewuf2iUBqJtzwb9lF8o/JtZ1ZZ9okBZANTk=,tag:66F8fqPoMXDnk5i2wlSQDw==,type:str]
    namespace: ENC[AES256_GCM,data:WJ2Or90y,iv:v/l7acIxz5LQgfdHep6TzSXcHs7pBA8mUvlvlKrDo9E=,tag:Kstwr15XZi/L5Z3SLSTF9Q==,type:str]
type: ENC[AES256_GCM,data:cqkHdHPS,iv:XgJUjwbDVvYVn4PShdlTwLDg4ZZFiw1y55PLdTFBGYU=,tag:BKvFS4mguPhXP4nsxfXL1w==,type:str]
stringData:
    KOPIA_REPOSITORY_PASSWORD: ENC[AES256_GCM,data:P3rR0UQVeZD2uonX++zeuTRHzF0N57a/gQ7pxitXNeE78IIz8wa5iUxD+IKxHKMK4qcM1lRsPj73+nZ49jF+pA==,iv:b39MfAOqp26HxQDrzLpu5SUywibSsJjE92iMZV9sRWg=,tag:aFTigvic8iK9tBnJT+slvQ==,type:str]
    KOPIA_SERVER_HOSTNAME: ENC[AES256_GCM,data:YbZhrn/z/rp5WzWLFwxm2k4=,iv:PS9ccLQBwtuy32PYgW1rAEwrTjvOF1zemW1syDAUsEc=,tag:j83ufWjxVND57NaUZLUNBw==,type:str]
    KOPIA_SERVER_USERNAME: ENC[AES256_GCM,data:6+vo0lcezheQzHJWPCHeTEmEilUmxE3VRk/cOejprr8RvsGLOn53mY6rpApWGfr0MfHHAAqUZr+tBHBy9thcoQ==,iv:s2IL+8dVEtLpgLUA+wflMzS1RkrAH0SBwU7QANJ6K4o=,tag:+y88EpqsdhBRTPBY4dKJXg==,type:str]
    KOPIA_SERVER_PASSWORD: ENC[AES256_GCM,data:/q+3TaK9vNda25qxGW8er1F6mzQsE1yO2GWjfiUs8AcEdE7hYDuw9KwffsST92vdprO7BxgUqcgH8W+v4EZZTQ==,iv:aIdam5gTJIZbN2urBqNAGhsm7G45TXdjdtEAOy+Ydqw=,tag:GZQ/RjFlMyGmj1FAwHXiWQ==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTi9iQ21POGFQTTZ5Z3R1
            UUdOTERuRThKWGZNSi9RNFROdTB4ZzhkekVjCnFSRCtBVEo2eHlxbXZuSllUeng1
            Mk82ZmRJOFUrcm5IS1hnb2MvVDV1SGMKLS0tIFFsRjlWRllWSGRQN3J0aW53VENP
            bTdMZ1RPWW5mYmg2KzB2SVhiclhGQzAK75ny0Egqsd/9yHl60J3nAEuKZGvynUKS
            YGnT5Yjx/yID2/Rh8k3Fhm89DiwLBZsmVetMlb9uKoyIrXoTkETr8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T09:28:36Z"
    mac: ENC[AES256_GCM,data:By2jvTAgeEjNWm1yqk/bDma+cZ+XzIkgRcwVTO/uSzFeU1UyKRO9W0f6BwOCUr3614rKdbo9lmMSL3RCydzQZleHKHwzl1Ozgl14sBQ1SEV8C8otfawMGAeHc0ca58P70aZscZ4HR+Oyy2N+uYWWr8MfBCkMDMnX4d2gmgBLDpM=,iv:2vUpl+8W7T+ZfFvx9OZ/ftHD2fZviM1mgGaldZrv4GA=,tag:ZNe/WwFMTB4jyh9fnTKNXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:v14=,iv:CXX6p/PzL9+f30EZAeASN9AkqVwBtCZbvQzuZwwkh6Y=,tag:a61kQ4e1cV3riA/7UdLieA==,type:str]
kind: ENC[AES256_GCM,data:XDBWhouX,iv:X4xx+E6FxGlPP2TB7lqkB5okv49cTahoeRuY8zj8/qY=,tag:PYkt/fnsDm8EvmNd57ahhg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Y0aSAYdwMMAaUTFW8lcasg==,iv:ogOuHU3M5T/FQEySshS0AEK1EKYgcFU9NwgQ+a+1Ni4=,tag:rn3NFIKSvkgU+KJ5PkLG0g==,type:str]
    namespace: ENC[AES256_GCM,data:3e+/+9j+,iv:Jea1xW312VuHjmq0XiCeXAVBADr4I3HsdD8WWLidTjI=,tag:UhU71D80xDry0W0Zor3ntg==,type:str]
type: ENC[AES256_GCM,data:FPvhWFqP,iv:lE2VFfYsIwUywEeQRtdiNuTt+8f7c/KZC/zIO41DKpM=,tag:4NkV+FAHhuEexyPBudPJfw==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:vQAbXb4Y39omgdP+cno1qeHd1ISA+Xe0ZZzwWRvHiyXKVcAKmel+OcKQA1y7qYz7pZ0DVg/NQ8EX9BXVNHSNlg==,iv:YqEWjXmGk/qFsB4g54OpbBKIT2+EFRPa2ANqDJkg9d4=,tag:EmtWbLpb8VrXYHHmU12oYw==,type:str]
    password: ENC[AES256_GCM,data:Eqg/0G9BYpXzCJ1TLH9xM07JaqQo+mDbyQ2Q4Tp7mvoXgjZ0KN5cax6dyptz5lm41W+VV31PGo/c+jN3+EWSyw==,iv:7TkGMA35WUhCt4OIbomwRwbZeIIzEmsqh24hKP9Y3sQ=,tag:pUN1FO50e5vyV11gBu39kA==,type:str]
    replication-password: ENC[AES256_GCM,data:C8B4HTwzVxT6ydCLsxbTn6E9U5N90euczv5dsoULcwFGYso8mEOIE7/EYfEJQfX5DYGHnlxvqUiSc5lMnMbCmQ==,iv:to+qClU8QkIoOv0hiSd3+xDcW+IjmZfNSj5YFNLfarA=,tag:kgSQ0jeAdzc75RhC+Dyeqg==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTi9iQ21POGFQTTZ5Z3R1
            UUdOTERuRThKWGZNSi9RNFROdTB4ZzhkekVjCnFSRCtBVEo2eHlxbXZuSllUeng1
            Mk82ZmRJOFUrcm5IS1hnb2MvVDV1SGMKLS0tIFFsRjlWRllWSGRQN3J0aW53VENP
            bTdMZ1RPWW5mYmg2KzB2SVhiclhGQzAK75ny0Egqsd/9yHl60J3nAEuKZGvynUKS
            YGnT5Yjx/yID2/Rh8k3Fhm89DiwLBZsmVetMlb9uKoyIrXoTkETr8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T09:28:36Z"
    mac: ENC[AES256_GCM,data:By2jvTAgeEjNWm1yqk/bDma+cZ+XzIkgRcwVTO/uSzFeU1UyKRO9W0f6BwOCUr3614rKdbo9lmMSL3RCydzQZleHKHwzl1Ozgl14sBQ1SEV8C8otfawMGAeHc0ca58P70aZscZ4HR+Oyy2N+uYWWr8MfBCkMDMnX4d2gmgBLDpM=,iv:2vUpl+8W7T+ZfFvx9OZ/ftHD2fZviM1mgGaldZrv4GA=,tag:ZNe/WwFMTB4jyh9fnTKNXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:iAc=,iv:6rmdEJ3954VXNl8v43H/1IUZ2Ney0U3P2Lcn9FiO/b8=,tag:9wgVwpOJqSoWxJkC3ptA7g==,type:str]
kind: ENC[AES256_GCM,data:DD5V118a,iv:tI/2l5dJpMWFfUUwkJnKJrxjeC3wgS0Jdqg+ZUJnoLk=,tag:rHZkvQRwB4tStUIKC7GjRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hFH+LD1ierxF/TFKKWSbuMKCEQ==,iv:waDEqTg+7PC1EFDY4I0q6uS6OsDk1jWPQd3ZEeLP2mQ=,tag:Z4IU14RwhZ5h8nb/xrNR+g==,type:str]
    namespace: ENC[AES256_GCM,data:BYpJO7VS,iv:ED2aZ0frbS1tNbTt1COfPuMYx3SAErsnHZWrMjx8wV8=,tag:qXNVBShH2B3zjWG9wyuVnw==,type:str]
type: ENC[AES256_GCM,data:D5AOPnMW,iv:4btIIB1ME2EnimRuQ556efP8whJyQr08ZctbJswu6Bs=,tag:AH1kWBpc/uq4clIO0RyOPA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:9+kRfgPJrRXj4Aux0XP4gEOOsp3pZ51vbjHDk0Fzp8ePJXNpMRgFBoIX1c8C1pe2boUBoQJgoC7XoK2qgAB2bw==,iv:lxW9fi2FnfCrdTxGtrU0iEz6YGmMuUqcWo7xep+xE2Y=,tag:JPI2GY84cKIKpGhY944lAw==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTi9iQ21POGFQTTZ5Z3R1
            UUdOTERuRThKWGZNSi9RNFROdTB4ZzhkekVjCnFSRCtBVEo2eHlxbXZuSllUeng1
            Mk82ZmRJOFUrcm5IS1hnb2MvVDV1SGMKLS0tIFFsRjlWRllWSGRQN3J0aW53VENP
            bTdMZ1RPWW5mYmg2KzB2SVhiclhGQzAK75ny0Egqsd/9yHl60J3nAEuKZGvynUKS
            YGnT5Yjx/yID2/Rh8k3Fhm89DiwLBZsmVetMlb9uKoyIrXoTkETr8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T09:28:36Z"
    mac: ENC[AES256_GCM,data:By2jvTAgeEjNWm1yqk/bDma+cZ+XzIkgRcwVTO/uSzFeU1UyKRO9W0f6BwOCUr3614rKdbo9lmMSL3RCydzQZleHKHwzl1Ozgl14sBQ1SEV8C8otfawMGAeHc0ca58P70aZscZ4HR+Oyy2N+uYWWr8MfBCkMDMnX4d2gmgBLDpM=,iv:2vUpl+8W7T+ZfFvx9OZ/ftHD2fZviM1mgGaldZrv4GA=,tag:ZNe/WwFMTB4jyh9fnTKNXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:kBQ=,iv:LXFSsl99i0xoUufLMbrWS+irwPBrJJDHdRBqkJfcFFM=,tag:INAIrIXJOxrNzySPmy50Cw==,type:str]
kind: ENC[AES256_GCM,data:Vnk0R9nV,iv:t52UhFKoFsk72POCWiJ7sIYjVWmQGsksfT2s2I0EesQ=,tag:/x+yYUKUQxmfpTeendXjtg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LV24L9Vvn4dwazZcO6xpn0Me,iv:zXSYHgI+nva2x2DVLmkZpq/oXD/rqqevQ4A8q++ccY4=,tag:iSLFGIkYopdzasVILdUMUg==,type:str]
    namespace: ENC[AES256_GCM,data:pTygBGx7wtrbBK8=,iv:9GPEet7gJf2smIpEGAhzf6Ns7uSIPheKrCBBytb9HrA=,tag:D8hlLX12wNjrUx6AzFz44w==,type:str]
type: ENC[AES256_GCM,data:Rw7fM2cR,iv:E853T8czpHWo2AGdoMFa5BBXHgNSj0CvIChp1cEA51I=,tag:xPVz/levwvy2zftWKN3+JA==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:e18//Psrcvc9vxlt1I5vKKNGLL9diotCTMShBC1sHtrMVoxFTj3Dy33j8X5UGTOanz2nSM+WqzBIthgttdz/sw==,iv:QXqcBkwYvVLFRq5heCVOmyPALWLbMhMcMJU9AOJYsgo=,tag:mxl43nTeioOwAHkKuaf8Ew==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTi9iQ21POGFQTTZ5Z3R1
            UUdOTERuRThKWGZNSi9RNFROdTB4ZzhkekVjCnFSRCtBVEo2eHlxbXZuSllUeng1
            Mk82ZmRJOFUrcm5IS1hnb2MvVDV1SGMKLS0tIFFsRjlWRllWSGRQN3J0aW53VENP
            bTdMZ1RPWW5mYmg2KzB2SVhiclhGQzAK75ny0Egqsd/9yHl60J3nAEuKZGvynUKS
            YGnT5Yjx/yID2/Rh8k3Fhm89DiwLBZsmVetMlb9uKoyIrXoTkETr8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T09:28:36Z"
    mac: ENC[AES256_GCM,data:By2jvTAgeEjNWm1yqk/bDma+cZ+XzIkgRcwVTO/uSzFeU1UyKRO9W0f6BwOCUr3614rKdbo9lmMSL3RCydzQZleHKHwzl1Ozgl14sBQ1SEV8C8otfawMGAeHc0ca58P70aZscZ4HR+Oyy2N+uYWWr8MfBCkMDMnX4d2gmgBLDpM=,iv:2vUpl+8W7T+ZfFvx9OZ/ftHD2fZviM1mgGaldZrv4GA=,tag:ZNe/WwFMTB4jyh9fnTKNXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:xgg=,iv:lpyIHTcmfmDaxiIYZIq9BNrdul3zBFqCR6o/MduXj8s=,tag:go+N/bWr0PadStwxirQyfA==,type:str]
kind: ENC[AES256_GCM,data:qgo0C3O5,iv:rA1NTmHakmurY+QhdM9Hm5zRFW4OR1H1ebU9dTmcfEQ=,tag:6RCkd/2Na65FBm+YpxMbrQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XjuOSnVYhqnyy8APgt8=,iv:y/DMR1894QevvEpo94h5CeyHBZUMIR/V7oCAmvXcRIs=,tag:clVNcKfv+5QfUv5BXl6HqQ==,type:str]
    namespace: ENC[AES256_GCM,data:JPYDlBbH1g==,iv:nmRWCCJFDhfNyjuF5cK75bJ3Px0qpRB3xsOKCvzse/0=,tag:5ocsujjFu7YZT92w8gEgHQ==,type:str]
type: ENC[AES256_GCM,data:v7YBWp2O,iv:e53zGcRsDSsP3da9FHUKgQbw073wP0wRRJPhVYJWD/M=,tag:/rRxeEU8dmdF4VO0qxASFA==,type:str]
stringData:
    TUWUNEL_REGISTRATION_TOKEN: ENC[AES256_GCM,data:2+B91H5fJxgVCyl8Xx3BBUO6Ey+LMRfrExRYT75PHxE1+7Xj9EbXfrtcStDam3U14Qw1LGpnhypxOdxtLJa4uQ==,iv:0HG+y+d75s+NG567iZfqtxAaCZJNqsSPrntB4bpMAR8=,tag:tFukqD9Mn9ePlYpEA1aMYQ==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTi9iQ21POGFQTTZ5Z3R1
            UUdOTERuRThKWGZNSi9RNFROdTB4ZzhkekVjCnFSRCtBVEo2eHlxbXZuSllUeng1
            Mk82ZmRJOFUrcm5IS1hnb2MvVDV1SGMKLS0tIFFsRjlWRllWSGRQN3J0aW53VENP
            bTdMZ1RPWW5mYmg2KzB2SVhiclhGQzAK75ny0Egqsd/9yHl60J3nAEuKZGvynUKS
            YGnT5Yjx/yID2/Rh8k3Fhm89DiwLBZsmVetMlb9uKoyIrXoTkETr8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T09:28:36Z"
    mac: ENC[AES256_GCM,data:By2jvTAgeEjNWm1yqk/bDma+cZ+XzIkgRcwVTO/uSzFeU1UyKRO9W0f6BwOCUr3614rKdbo9lmMSL3RCydzQZleHKHwzl1Ozgl14sBQ1SEV8C8otfawMGAeHc0ca58P70aZscZ4HR+Oyy2N+uYWWr8MfBCkMDMnX4d2gmgBLDpM=,iv:2vUpl+8W7T+ZfFvx9OZ/ftHD2fZviM1mgGaldZrv4GA=,tag:ZNe/WwFMTB4jyh9fnTKNXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
