apiVersion: ENC[AES256_GCM,data:1Qs=,iv:FsxwzCRZLdH0ngks2zEPdCl2nCIchtJI/JRDT7nYzK8=,tag:HvnEYjyR2tZzMXFPT0W0cw==,type:str]
kind: ENC[AES256_GCM,data:g747GHpe,iv:2k1J4QjCFYlvXXlkzhJL/Y8zq/mSO4XyCYbVKCy8ozE=,tag:xnYymTmSbyerDycujQp2Ow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qTubWnDZMiiaZrI=,iv:/Gt+hUWEyRDcPBRTEXcxqcNjzkniKLG04WMVEQudSxc=,tag:nmOP4uE16H9sPTOgt9xmFA==,type:str]
    namespace: ENC[AES256_GCM,data:gRjWsgRT,iv:QFSCTnBAWoKMMRkRwppKJrdVCuIQ3HRSCBJjTSgtFp8=,tag:u3ueCfCBVRmqqfXPVjzc7Q==,type:str]
type: ENC[AES256_GCM,data:q5NawtgR,iv:wVYTa5Vi97v4xVRUB1WrPoZnIfMTt87LleJHSvLQzHs=,tag:PCNTcH710lQQfEgRUpsSIA==,type:str]
stringData:
    SQLD_AUTH_JWT_KEY: ENC[AES256_GCM,data:f8xgmhDwYU4w2qo1PfhGEttfEbke4MLjDMGWoxgL2heVNdoy/7Sh2aSuURvhfeI/Pu5oq9EVK4/DU07xyodD/Q==,iv:EbbzH4xtf0RVH21llvHAwxApH2TBXf/HeQpJJkAGQZI=,tag:i/oKcQ2fqwm20Q38psq7Nw==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Qko3ZmVsMXh5Q3d0YjE5
            RzhveUZTOHFDRERCSmtVR1d2TW4zaGZOTkNjCkJXMFhoenU3R1hEcFc2TTRsc0Ux
            bk84Qm5XZWpUUzI3d3RMOEdOV1lMMG8KLS0tIEljV0FaYmZxK1dBSTV6YmlzYytT
            TDhYRHVTR09scVM4aHVGK3MzaEhmU0UKcTK/e40SjVoz40bDhHwHCQ63RKIPd58S
            ysEW0Hy1364pAffp6du0REi7RUYVpj/HhKmzk4ZfmGSzOon6ooP6Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:10:40Z"
    mac: ENC[AES256_GCM,data:rSlqT8Qnu4P2yblw4rUrlzuE+810ADvWXvYUsTVZ7jaVwqctpXsnYRq8Hji3jLDIqG2RJ5MulHMxmki6wBj3tK4Bpy9u0WmiHVJf5vWQS4xIWbxAQ0Brx9+LCEpAQ1TuMCKTyU2zhN2V4brQF4vB7nO/jhXkr0KRjRArRqG7XpQ=,iv:Dgmgg8Fbpn0hQQNp6hpu7k/3c5LpidqjX0335mdx9hU=,tag:Rvz300KQcvZT6C8jA9OK9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:y6U=,iv:kdtbTDgOUDUMvgpO/inMVsGVTbYI/RU6AwXjvW7/L/Q=,tag:RoWHkS0oRr2tma63PJ6XPQ==,type:str]
kind: ENC[AES256_GCM,data:Frk1tkCf,iv:y+OI8MvmFHmZ/Cw68zRSZGbS9pMqU0SduqTSFgk4Bv4=,tag:PP3lYSnr52CYWNGSyVSoPg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0ozdI+3YSh/jGA==,iv:/6e6cDnJciZqAJ+3dYBE1sHMk3So/B7nJDdv3KdnPs4=,tag:DyKDuBnM7nLCHLzxD4Zj5Q==,type:str]
    namespace: ENC[AES256_GCM,data:QjVdyZoc,iv:JRqg5H6lB/v2gFEzf1n23PSR6McGdB4b8/0BGoWyjLU=,tag:BXV1xR6k2vySJenn4grZRg==,type:str]
type: ENC[AES256_GCM,data:O+vNZZVI,iv:5rCdW/1jPOLFvfILlZebbbaEAq1iyVJS3OjXLVQHYVo=,tag:LGUT9tPjSF3n1Y/Ift3loA==,type:str]
stringData:
    KOPIA_REPOSITORY_PASSWORD: ENC[AES256_GCM,data:l9sAjeX7MhulemldEWzxWtlXWyzDLUMv79zHc1dK9rpz6Lb9eJ0vhHb3DeDXsu5D2t963L+lEMWbFRMX1PKMHQ==,iv:yJgMAiQS35GuTaYG+QBXg/Nfihv6P3OXA/LynaIOgdI=,tag:5ulYmBWqinJWNKrkqCRKpQ==,type:str]
    KOPIA_SERVER_HOSTNAME: ENC[AES256_GCM,data:5Iww54Uv548cIE6S6svhog8=,iv:OsHbsSo55XQtz/i2UlaqJfaGNqD5PtCDyS62XCeR304=,tag:k/Zmx5SKstkpgrzyD9G3cQ==,type:str]
    KOPIA_SERVER_USERNAME: ENC[AES256_GCM,data:PRGv501MH2Pn/r4PsVIvRVSN/+HJ0G9ErI+/nGrKiZVzY8SLgNNZ+1ALTjmM8GTqU8YGeLnKkG41aHUNoBv+eA==,iv:5UoqQlTG96CC14+CjNHnUNKuyTzvQi7okGF3JawnQUM=,tag:1vJzYi5ggM/PFqqoRCCJ2g==,type:str]
    KOPIA_SERVER_PASSWORD: ENC[AES256_GCM,data:WDbpc3wJeUJUqWkAWGMk/ZBE8R6WpN6e7U48ystyy5fIxVi2EZKNmPzo85HEtTC7bb7zYkbs4F2IJo4tnW0yDw==,iv:CWy5Jlgf8sw3NSx8LlKJ0fgoCnYiOv0w+e0EefJMAsY=,tag:BH0DTmDX13pr/Jhu436xLQ==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Qko3ZmVsMXh5Q3d0YjE5
            RzhveUZTOHFDRERCSmtVR1d2TW4zaGZOTkNjCkJXMFhoenU3R1hEcFc2TTRsc0Ux
            bk84Qm5XZWpUUzI3d3RMOEdOV1lMMG8KLS0tIEljV0FaYmZxK1dBSTV6YmlzYytT
            TDhYRHVTR09scVM4aHVGK3MzaEhmU0UKcTK/e40SjVoz40bDhHwHCQ63RKIPd58S
            ysEW0Hy1364pAffp6du0REi7RUYVpj/HhKmzk4ZfmGSzOon6ooP6Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:10:40Z"
    mac: ENC[AES256_GCM,data:rSlqT8Qnu4P2yblw4rUrlzuE+810ADvWXvYUsTVZ7jaVwqctpXsnYRq8Hji3jLDIqG2RJ5MulHMxmki6wBj3tK4Bpy9u0WmiHVJf5vWQS4xIWbxAQ0Brx9+LCEpAQ1TuMCKTyU2zhN2V4brQF4vB7nO/jhXkr0KRjRArRqG7XpQ=,iv:Dgmgg8Fbpn0hQQNp6hpu7k/3c5LpidqjX0335mdx9hU=,tag:Rvz300KQcvZT6C8jA9OK9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:PEQ=,iv:Lzht0s/reKyM+Qal/XFfTlQ1MsXDc1sYYs2uX7sNsu4=,tag:2pM2lMyXhYe5OSwkbLXi9g==,type:str]
kind: ENC[AES256_GCM,data:Ze8I0TWK,iv:5MH6HVjnuJ+Uqd1KGphLGpH1Awx0Gx8qu1FwkFuORis=,tag:HAQkEDIBpxN9TZY8+E1vdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Km3XAALp6qcTDI9qOX2h6A==,iv:NzDMmxMlTEE/o7CDAhbNkZNu1k9VgLN37HdvaE0VbfM=,tag:kx0bv+DftqoHVH4wuRNHdw==,type:str]
    namespace: ENC[AES256_GCM,data:D1LyfkRr,iv:Ht1TuftvD2RCstUkE1uUv/7WS4qNLSE1L6c9sUtcYNE=,tag:eJFejaTE2iz84EkD8uSeEA==,type:str]
type: ENC[AES256_GCM,data:OUd8Er87,iv:h+P79culjMMEk+39DLNTmEdNUgD0HP+ESS8DoxGH4Jc=,tag:6ZELI+QNVqgLj0RyruvbKA==,type:str]
stringData:
    postgres-password: ENC[AES256_GCM,data:OOtgSQD6YpGo1+oGLBUrNvPNXUbAaAE2tyvYTFsY4dVUGuC9PyWbkwulfPQzsekJwzP8bi+5+XaqwmuoKRBu5g==,iv:XoAjciIWI4i9w4R2Ug6YfnTEfMLAd+OGWoFpk+VHSDU=,tag:W5aQhLir1WOfcd4dbB9dxQ==,type:str]
    password: ENC[AES256_GCM,data:L7tzwpscj1g/r7zJ9bNMl73OsaGM43N3UbuVN66Gr7IH2pXbY3DNsZk+9BSPQUKzsPOQaGp8XgRbdiy9aKU8iQ==,iv:EcIXpa1d/PMyxV4tPKj40fb4wVeLh39eLSl3zWz7LfQ=,tag:xdRX5FOaB5/peMp9cIdQiQ==,type:str]
    replication-password: ENC[AES256_GCM,data:A07qERqn5j++AE82gqONse1xM14AP+AK4ssO3jfKlu2U3idLMQfb+1VYRpu/RQ4ix4VwlTkGNIYoxJi4OUBgOw==,iv:43YZf4wrfWOL570fS3L0hAKBn5j0pzA0lgPLrxF0aGw=,tag:s7rLbV6NaxbluiPXZc+xuA==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Qko3ZmVsMXh5Q3d0YjE5
            RzhveUZTOHFDRERCSmtVR1d2TW4zaGZOTkNjCkJXMFhoenU3R1hEcFc2TTRsc0Ux
            bk84Qm5XZWpUUzI3d3RMOEdOV1lMMG8KLS0tIEljV0FaYmZxK1dBSTV6YmlzYytT
            TDhYRHVTR09scVM4aHVGK3MzaEhmU0UKcTK/e40SjVoz40bDhHwHCQ63RKIPd58S
            ysEW0Hy1364pAffp6du0REi7RUYVpj/HhKmzk4ZfmGSzOon6ooP6Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:10:40Z"
    mac: ENC[AES256_GCM,data:rSlqT8Qnu4P2yblw4rUrlzuE+810ADvWXvYUsTVZ7jaVwqctpXsnYRq8Hji3jLDIqG2RJ5MulHMxmki6wBj3tK4Bpy9u0WmiHVJf5vWQS4xIWbxAQ0Brx9+LCEpAQ1TuMCKTyU2zhN2V4brQF4vB7nO/jhXkr0KRjRArRqG7XpQ=,iv:Dgmgg8Fbpn0hQQNp6hpu7k/3c5LpidqjX0335mdx9hU=,tag:Rvz300KQcvZT6C8jA9OK9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:E9g=,iv:cnWHFFx0mwHuJEeCmld6WQT/x20rKI8AR3rO9ndlG6M=,tag:cEyQ6YW+FHKNxiyJm2393A==,type:str]
kind: ENC[AES256_GCM,data:fQFQYQIr,iv:6HJtpY8FTM+cNWLDUhRE2a9aOG/mwoxacB7eL8HQWOk=,tag:4VJqrT8fo8P/Wpf/6Pgf/g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LJw7kX3qW1MhiYEsximVLtm3Mg==,iv:W/ZbpXuUtbg8SvE4cImUxrAEb6mYjc9nFIZlA2R2TH8=,tag:8cGi7A+Miaiiev+aB7sc4w==,type:str]
    namespace: ENC[AES256_GCM,data:FlZrZdbk,iv:sEIw28JuCLUL4N1nIQ3x4ql1IR42htPYbqGbf2GCYfY=,tag:770zb7AAk/EVekkJgFrvPw==,type:str]
type: ENC[AES256_GCM,data:kEGztbZu,iv:1nC+ktfo31+oINBBgeRwAVKlolwoJaWwCTpdW4MS6Iw=,tag:AlhNmgbS5vIjIf/G09c3cg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:R2Pce8+4oJj/Er0+DYR3a68W6rZHYm3Mu61PYbAgtlv5TSpzSjUtZQWlOW1mV1lYPnnAlYCRLueG2NNpS1xxag==,iv:g8u5gogFqTCAXFP8B2JnC/p/momwV4IZ14kSyisg7u0=,tag:XuaxaeYHCgcDRM9k7T4Ofg==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Qko3ZmVsMXh5Q3d0YjE5
            RzhveUZTOHFDRERCSmtVR1d2TW4zaGZOTkNjCkJXMFhoenU3R1hEcFc2TTRsc0Ux
            bk84Qm5XZWpUUzI3d3RMOEdOV1lMMG8KLS0tIEljV0FaYmZxK1dBSTV6YmlzYytT
            TDhYRHVTR09scVM4aHVGK3MzaEhmU0UKcTK/e40SjVoz40bDhHwHCQ63RKIPd58S
            ysEW0Hy1364pAffp6du0REi7RUYVpj/HhKmzk4ZfmGSzOon6ooP6Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:10:40Z"
    mac: ENC[AES256_GCM,data:rSlqT8Qnu4P2yblw4rUrlzuE+810ADvWXvYUsTVZ7jaVwqctpXsnYRq8Hji3jLDIqG2RJ5MulHMxmki6wBj3tK4Bpy9u0WmiHVJf5vWQS4xIWbxAQ0Brx9+LCEpAQ1TuMCKTyU2zhN2V4brQF4vB7nO/jhXkr0KRjRArRqG7XpQ=,iv:Dgmgg8Fbpn0hQQNp6hpu7k/3c5LpidqjX0335mdx9hU=,tag:Rvz300KQcvZT6C8jA9OK9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:3mk=,iv:LaBhYjsimviRXDqC4F8LKllA/DCwZR/jf0xUslKUyDI=,tag:GtIbcSUWdqrbw+EO/9gkLQ==,type:str]
kind: ENC[AES256_GCM,data:1HBTfANP,iv:opDxhKjaydlljQmFKpim0/0prGqgVIqStP5fFPRHYtU=,tag:w2DcnpXPyl71WwtMg1CEbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SQWfEONuziocN//++Sd2hgA1,iv:Y1grXsM/gTCtYoCGuWuR81llhaeC1jaFfqLatKOndKs=,tag:6cr+lL/bn+wVsPtEn5D+fA==,type:str]
    namespace: ENC[AES256_GCM,data:MULhx8TGjX0y/mA=,iv:5Ddb9O3gy7SBWY8OvvgCgQMWESOdBvlVzgzZX7uY9Ok=,tag:wIsmeOux1znSGBy96icRrg==,type:str]
type: ENC[AES256_GCM,data:ad4DaQfJ,iv:BNZqexhtjF7p2hPITA8xhaeG0EVPcqb/SznL7+jN6Qg=,tag:BvEdKeM7UHWsqRuALy6jDA==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:K1u4xKgGG2X0EqFzIEDk9aZma3GoEsXbLHeac3kGdbdmkdzvieqAG/DSiswGRR31UEr0HTznIVMF3yenxThaWQ==,iv:eQBEf+0kc9s0ZSUkF+QGIWU/cGKgXm8Ko/mNAyl6Cq0=,tag:SiGMSC8tBowGj+RZR8ynHw==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Qko3ZmVsMXh5Q3d0YjE5
            RzhveUZTOHFDRERCSmtVR1d2TW4zaGZOTkNjCkJXMFhoenU3R1hEcFc2TTRsc0Ux
            bk84Qm5XZWpUUzI3d3RMOEdOV1lMMG8KLS0tIEljV0FaYmZxK1dBSTV6YmlzYytT
            TDhYRHVTR09scVM4aHVGK3MzaEhmU0UKcTK/e40SjVoz40bDhHwHCQ63RKIPd58S
            ysEW0Hy1364pAffp6du0REi7RUYVpj/HhKmzk4ZfmGSzOon6ooP6Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:10:40Z"
    mac: ENC[AES256_GCM,data:rSlqT8Qnu4P2yblw4rUrlzuE+810ADvWXvYUsTVZ7jaVwqctpXsnYRq8Hji3jLDIqG2RJ5MulHMxmki6wBj3tK4Bpy9u0WmiHVJf5vWQS4xIWbxAQ0Brx9+LCEpAQ1TuMCKTyU2zhN2V4brQF4vB7nO/jhXkr0KRjRArRqG7XpQ=,iv:Dgmgg8Fbpn0hQQNp6hpu7k/3c5LpidqjX0335mdx9hU=,tag:Rvz300KQcvZT6C8jA9OK9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:7gY=,iv:P21q7LL8+fvv4YW6DWqmGC21dNjsov/GrvwWXMtz1y8=,tag:bV4UFo5/ITIlQ9yhLgG3/g==,type:str]
kind: ENC[AES256_GCM,data:wrRuPyVv,iv:Im4vwRHTQTgcnaQA48RzxZR8WQgHYPRszdZlDRQr/YM=,tag:18U8XujwY559gnwpEcuBfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZKLVJZzpUPyH/WaKfNk=,iv:CXQ+lUUZoAxds/MGfcU3cZOBUab2uIo+w9ZgrBJWU2s=,tag:6XhIjKvAeVVceN9MGMA3HQ==,type:str]
    namespace: ENC[AES256_GCM,data:Nl6mZROEkA==,iv:zivasAx6Yb6dwTvp/bsozqnbgnFgVL3Y6KSqhqV4YE4=,tag:5JSPoyJKENNlTXg30ov1Dg==,type:str]
type: ENC[AES256_GCM,data:ObC3eoEg,iv:Sqtrp+waHWRFA3KaHiUPS0DxPhGIypP4Khat8C7pXqs=,tag:IakxJ/asbuoXyLE9BOAJqw==,type:str]
stringData:
    TUWUNEL_REGISTRATION_TOKEN: ENC[AES256_GCM,data:QOxRsr5XZm8M5E9a5BZMawOpQTdz5yZOaQGycAuIzPduzudPoo9OkV4zwLpWhixUJIyXCOL+8ATaJEwLMTeTgA==,iv:mgkrIqvevIQCnvrcj2Q6PX3N01kdksW29bVr/T81r/M=,tag:HR/3S5bjR/lmWqj9rGaVkg==,type:str]
sops:
    age:
        - recipient: age1w9s7424jtltmns70e4xw5u7gnnktxdn2de0ssvapee7lvp7xtyeskyrylx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Qko3ZmVsMXh5Q3d0YjE5
            RzhveUZTOHFDRERCSmtVR1d2TW4zaGZOTkNjCkJXMFhoenU3R1hEcFc2TTRsc0Ux
            bk84Qm5XZWpUUzI3d3RMOEdOV1lMMG8KLS0tIEljV0FaYmZxK1dBSTV6YmlzYytT
            TDhYRHVTR09scVM4aHVGK3MzaEhmU0UKcTK/e40SjVoz40bDhHwHCQ63RKIPd58S
            ysEW0Hy1364pAffp6du0REi7RUYVpj/HhKmzk4ZfmGSzOon6ooP6Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:10:40Z"
    mac: ENC[AES256_GCM,data:rSlqT8Qnu4P2yblw4rUrlzuE+810ADvWXvYUsTVZ7jaVwqctpXsnYRq8Hji3jLDIqG2RJ5MulHMxmki6wBj3tK4Bpy9u0WmiHVJf5vWQS4xIWbxAQ0Brx9+LCEpAQ1TuMCKTyU2zhN2V4brQF4vB7nO/jhXkr0KRjRArRqG7XpQ=,iv:Dgmgg8Fbpn0hQQNp6hpu7k/3c5LpidqjX0335mdx9hU=,tag:Rvz300KQcvZT6C8jA9OK9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
